### ISSUE TITLE
Demo got blank page in Safari

### ISSUE THREAD

**Issue by nvcken** [gearz-lab/react-metaform#11]
I try open demo in Safair, and it's blank page.
Need double check.
```
[Error] SyntaxError: Attempted to redefine property 'schema'.
	(anonymous function) (bundle.js, line 24)
```

**Comment by andrerpena** [comment]
Thank you for reporting.
Do you have any idea of how to test it on Windows given that Apple discontinued Windows support?

**Comment by andrerpena** [comment]
This seems to be related: https://github.com/ember-cli/ember-cli/issues/3957

**Comment by andrerpena** [comment]
I seem to have found the problem.
@nvcken, can you please verify if the demo works now?

**Comment by nvcken** [comment]
Cool, It works now.
Could you please give any detail of what problem ?
Thanks

**Comment by andrerpena** [comment]
Great.

As you can see [here](https://github.com/gearz-lab/react-metaform/commit/b41368fff774b6b21fa0c2b346f6608ef7baf365), the LiveSchemaEditor was declaring the MetaForm with duplicate props. When Webpack compiles the JSX, it generates a JSON with a field for each of the props. Safari is not tolerant to JSON with duplicate fields.

Thanks for reporting.
